version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: gst_mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: gst_rabbitmq
    ports:
      - '5672:5672'      # RabbitMQ broker port
      - '15672:15672'    # Management dashboard port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mongo_data:
  rabbitmq_data:
